<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QZBarberShopBooking.Application\QZBarberShopBooking.Application.csproj" />
    <ProjectReference Include="..\QZBarberShopBooking.Infrastructure\QZBarberShopBooking.Infrastructure.csproj" />
    <ProjectReference Include="..\QZBarberShopBooking.Service\QZBarberShopBooking.Service.csproj" />
  </ItemGroup>

</Project>
