<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QZBarberShopBooking.Domain\QZBarberShopBooking.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurations\" />
    <Folder Include="Data\" />
    <Folder Include="Interface\" />
    <Folder Include="Migrations\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

</Project>
